/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import {
  useCursor,
  useGLTF,
  useTexture,
  Float,
  Text3D,
} from "@react-three/drei";
import { useState } from "react";
import { useEffect } from "react";

export function SecondIsland(props) {
  const { nodes, materials } = useGLTF("/second-island.glb");

  const [hover, setHover] = useState(false);

  useCursor(hover);

  const tex = useTexture(
    "https://static.vecteezy.com/system/resources/thumbnails/050/703/718/small/set-of-contact-us-button-hand-pointer-clicking-contact-us-web-buttons-png.png",
  );

  const hoveredRef = useRef(null);
  const group = useRef(null);

  const handleClick = () => {
    let frame;
    const initialRot = group.current.rotation.y;
    const targetRot = initialRot + 2 * Math.PI;
    const duration = 600; // ms
    const startTime = performance.now();
    function animate(now) {
      const elapsed = now - startTime;
      const t = Math.min(elapsed / duration, 1);
      group.current.rotation.y = initialRot + (targetRot - initialRot) * t;
      if (t < 1) {
        frame = requestAnimationFrame(animate);
      } else {
        group.current.rotation.y = targetRot;
      }
    }
    frame = requestAnimationFrame(animate);
  };

  

  return (
    <group
      {...props}
      ref={group}
      dispose={null}
      onPointerEnter={() => setHover(true)}
      onPointerLeave={() => setHover(false)}
      onClick={handleClick}
    >
      <Text3D
        font={"/Inter.json"}
        position={[-190, 2, 10]}
        rotation={[0, 0.3, 0]}
        scale={15}
        bevelEnabled
        bevelThickness={0.1}
        castShadow
        receiveShadow
      >
        VisuaLab
        <meshStandardMaterial color={"#E6E6FA"} />
      </Text3D>
      <Text3D
        font={"/Inter.json"}
        position={[95, 3, 5]}
        rotation={[0, -0.3, 0]}
        scale={15}
        bevelEnabled
        bevelThickness={0.1}
        castShadow
        receiveShadow
      >
        Studios
        <meshStandardMaterial color={"#E6E6FA"} />
      </Text3D>

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.curve_Pipe}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_11.geometry}
        material={materials.island_Connector_CURVE}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_12.geometry}
        material={materials.island_Metal_holders}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_13.geometry}
        material={materials.machine_MAIN}
      />
      <mesh position={[2, 40, -20]}>
        <planeGeometry args={[37, 17]} />
        <meshStandardMaterial toneMapped={false} transparent map={tex} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_14.geometry}
        material={materials.machine_REACTOR}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_15.geometry}
        material={materials.machine_REACTOR_transparent}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_16.geometry}
        material={materials.machine_RENTGEN}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_17.geometry}
        material={materials.machine_TELEPORT_flash}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_18.geometry}
        material={materials.machine_TELEPORT_transparent}
      />
      <Float>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.BALOON}
        />
      </Float>
      <mesh
        ref={hoveredRef}
        castShadow
        receiveShadow
        geometry={nodes.Object_20.geometry}
        material={materials.ISLAND_BASE}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_21.geometry}
        material={materials.ISLAND_BASE}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_22.geometry}
        material={materials.machine_PRINTER}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_23.geometry}
        material={materials.machine_PRINTER}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_24.geometry}
        material={materials.machine_TELEPORT}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_25.geometry}
        material={materials.machine_TELEPORT}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_3.geometry}
        material={materials.BALOON_BULB}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.BALOON_CURVE}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_5.geometry}
        material={materials.DROPS_PIPE}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials.ISLAND_BASE_SHADOW}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_7.geometry}
        material={materials.base_island_additional_pipes}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials["base_island_additional_pipes_BEAM.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_9.geometry}
        material={materials.base_island_additional_pipes_transarent}
      />
    </group>
  );
}

useGLTF.preload("/second-island.glb");
